spring:
  jpa:
    properties:
      hibernate.dialect: "ca.uhn.fhir.jpa.model.dialect.HapiFhirPostgresDialect"
hapi:
  fhir:
    server_address: https://localhost:8080/fhir
    #server_address: https://hapi-fhir.au.localhost/fhir
    default_encoding: json
    # dao_config.server_id_mode: UUID
