FROM quay.io/keycloak/keycloak:26.0.7

# COPY /certs/tls.cert /opt/keycloak/tls.cert
# COPY /certs/tls.key /opt/keycloak/tls.key

# COPY /scripts/health-check.sh /opt/keycloak/health-check.sh
# RUN chmod +x /opt/keycloak/health-check.sh
